import json

import pytest

from company.runtime.github_client import (
    GitHubClient,
    GitHubError,
)


class FakeRunner:
    def __init__(self):
        self.calls = []

    def __call__(self, command):
        self.calls.append(command)

        if command[:3] == ["gh", "auth", "status"]:
            return ""

        if "git/ref/heads/main" in " ".join(command):
            return "abc123"

        if command[:3] == ["gh", "api", "repos/acme/app"]:
            return json.dumps(
                {
                    "owner": "acme",
                    "name": "app",
                    "default_branch": "main",
                    "html_url": "https://github.com/acme/app",
                }
            )

        if command[:3] == ["gh", "api", "repos/acme/app/git/refs"]:
            return ""

        if command[:2] == ["gh", "pr"]:
            return json.dumps(
                {
                    "number": 7,
                    "title": "Automated change",
                    "url": "https://github.com/acme/app/pull/7",
                    "state": "OPEN",
                }
            )

        return ""


def test_auth_status():
    runner = FakeRunner()
    client = GitHubClient(runner)

    assert client.auth_status() is True


def test_repository():
    runner = FakeRunner()
    client = GitHubClient(runner)

    repo = client.repository("acme", "app")

    assert repo.owner == "acme"
    assert repo.name == "app"
    assert repo.default_branch == "main"


def test_create_branch():
    runner = FakeRunner()
    client = GitHubClient(runner)

    client.create_branch("acme", "app", "ai/change-1", "main")

    assert any(
        "refs/heads/ai/change-1" in " ".join(call)
        for call in runner.calls
    )


def test_create_pull_request():
    runner = FakeRunner()
    client = GitHubClient(runner)

    pr = client.create_pull_request(
        "acme",
        "app",
        "Automated change",
        "Generated by the autonomous company.",
        "ai/change-1",
        "main",
    )

    assert pr.number == 7
    assert pr.state == "OPEN"


def test_merge_pull_request():
    runner = FakeRunner()
    client = GitHubClient(runner)

    client.merge_pull_request("acme", "app", 7)

    assert any(
        call[:3] == ["gh", "pr", "merge"]
        for call in runner.calls
    )


@pytest.mark.asyncio
async def test_async_pull_request():
    runner = FakeRunner()
    client = GitHubClient(runner)

    pr = await client.acreate_pull_request(
        "acme",
        "app",
        "Automated change",
        "body",
        "ai/change-1",
        "main",
    )

    assert pr.number == 7


def test_auth_status_returns_false_on_command_failure():
    def failing_runner(command):
        raise GitHubError("failure")

    client = GitHubClient(failing_runner)

    assert client.auth_status() is False
