from __future__ import annotations

import asyncio
import subprocess
from dataclasses import dataclass
from pathlib import Path

from src.github.automation.automation import GitHubAutomation
from src.github.client.http import GitHubHttpClient
from src.github.models.contracts import GitHubRepository


@dataclass(frozen=True, slots=True)
class GitOperationResult:
    success: bool
    message: str
    output: str = ""


class GitHubNativeService:
    """Repository lifecycle: clone, branch, edit, commit, push and PR."""

    def __init__(
        self,
        *,
        github: GitHubAutomation | None = None,
        git_executable: str = "git",
    ) -> None:
        self.github = github or GitHubAutomation(GitHubHttpClient())
        self.git_executable = git_executable

    async def clone(self, repository: GitHubRepository, destination: Path) -> GitOperationResult:
        destination.parent.mkdir(parents=True, exist_ok=True)
        url = f"https://github.com/{repository.owner}/{repository.name}.git"
        return await self._git(["clone", url, str(destination)], destination.parent)

    async def create_branch(self, workspace: Path, branch: str) -> GitOperationResult:
        return await self._git(["switch", "-c", branch], workspace)

    async def write_files(self, workspace: Path, files: dict[str, str]) -> None:
        root = workspace.resolve()
        for relative, content in files.items():
            target = (root / relative).resolve()
            if target != root and root not in target.parents:
                raise ValueError(f"Path escapes workspace: {relative}")
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")

    async def commit(self, workspace: Path, message: str) -> GitOperationResult:
        added = await self._git(["add", "--all"], workspace)
        if not added.success:
            return added
        return await self._git(["commit", "-m", message], workspace)

    async def push(self, workspace: Path, branch: str) -> GitOperationResult:
        return await self._git(["push", "--set-upstream", "origin", branch], workspace)

    async def publish_files(
        self,
        repository: GitHubRepository,
        branch: str,
        files: dict[str, str],
        message: str,
    ) -> GitOperationResult:
        """Create a branch and publish generated files through the GitHub API."""
        try:
            # A factory mission owns its repository. Create it on first use;
            # if it already exists, reuse it so retries remain idempotent.
            try:
                repository = await self.github.client.get_repository(
                    repository.owner,
                    repository.name,
                )
            except RuntimeError as exc:
                if "GitHub API 404" not in str(exc):
                    raise
                repository = await self.github.create_project_repository(
                    repository.owner,
                    repository.name,
                    description=f"Autonomous project generated by AI Software Company: {repository.name}",
                )

            base = await self.github.client.get_branch(
                repository,
                repository.default_branch,
            )
            try:
                branch_result = await self.github.client.create_branch(
                    repository,
                    branch,
                    base.sha,
                )
            except RuntimeError as exc:
                # Retries reuse the mission branch. GitHub returns 422 when
                # the branch already exists, which is safe and expected here.
                if "GitHub API 422" not in str(exc) or "Reference already exists" not in str(exc):
                    raise
                branch_result = GitOperationResult(
                    True,
                    f"Reusing existing factory branch {branch}",
                )
            if not branch_result.success:
                return GitOperationResult(False, branch_result.message)

            commit_ids: list[str] = []
            for path, content in files.items():
                result = await self.github.client.write_file(
                    repository,
                    path,
                    content,
                    message,
                    branch,
                )
                if not result.success:
                    return GitOperationResult(False, result.message)
                if result.identifier:
                    commit_ids.append(result.identifier)

            return GitOperationResult(
                True,
                f"Published {len(files)} file(s) to {repository.owner}/{repository.name}:{branch}",
                commit_ids[-1] if commit_ids else None,
            )
        except Exception as exc:
            return GitOperationResult(False, str(exc))

    async def open_pull_request(
        self,
        repository: GitHubRepository,
        title: str,
        branch: str,
        body: str = "",
    ):
        return await self.github.open_pull_request(
            repository, title=title, head=branch, body=body
        )

    async def _git(self, args: list[str], cwd: Path) -> GitOperationResult:
        def run() -> subprocess.CompletedProcess[str]:
            return subprocess.run(
                [self.git_executable, *args],
                cwd=cwd,
                text=True,
                capture_output=True,
                timeout=120,
                check=False,
            )

        try:
            result = await asyncio.to_thread(run)
        except (OSError, subprocess.TimeoutExpired) as exc:
            return GitOperationResult(False, str(exc))
        output = (result.stdout + result.stderr).strip()
        return GitOperationResult(
            result.returncode == 0,
            output
            or (
                "Git operation completed"
                if result.returncode == 0
                else "Git operation failed"
            ),
            output,
        )
